# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/nicos/OneDrive/Bureau/MAIN4/S7 - C++ POO/projet-cpp"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/nicos/OneDrive/Bureau/MAIN4/S7 - C++ POO/projet-cpp"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/nicos/OneDrive/Bureau/MAIN4/S7 - C++ POO/projet-cpp/CMakeFiles" "/mnt/c/Users/nicos/OneDrive/Bureau/MAIN4/S7 - C++ POO/projet-cpp//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/nicos/OneDrive/Bureau/MAIN4/S7 - C++ POO/projet-cpp/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named valeriePecrage

# Build rule for target.
valeriePecrage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 valeriePecrage
.PHONY : valeriePecrage

# fast build rule for target.
valeriePecrage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/build
.PHONY : valeriePecrage/fast

extlibs/Collision/Collision.o: extlibs/Collision/Collision.cpp.o
.PHONY : extlibs/Collision/Collision.o

# target to build an object file
extlibs/Collision/Collision.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/extlibs/Collision/Collision.cpp.o
.PHONY : extlibs/Collision/Collision.cpp.o

extlibs/Collision/Collision.i: extlibs/Collision/Collision.cpp.i
.PHONY : extlibs/Collision/Collision.i

# target to preprocess a source file
extlibs/Collision/Collision.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/extlibs/Collision/Collision.cpp.i
.PHONY : extlibs/Collision/Collision.cpp.i

extlibs/Collision/Collision.s: extlibs/Collision/Collision.cpp.s
.PHONY : extlibs/Collision/Collision.s

# target to generate assembly for a file
extlibs/Collision/Collision.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/extlibs/Collision/Collision.cpp.s
.PHONY : extlibs/Collision/Collision.cpp.s

src/Animation/Animation.o: src/Animation/Animation.cpp.o
.PHONY : src/Animation/Animation.o

# target to build an object file
src/Animation/Animation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Animation/Animation.cpp.o
.PHONY : src/Animation/Animation.cpp.o

src/Animation/Animation.i: src/Animation/Animation.cpp.i
.PHONY : src/Animation/Animation.i

# target to preprocess a source file
src/Animation/Animation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Animation/Animation.cpp.i
.PHONY : src/Animation/Animation.cpp.i

src/Animation/Animation.s: src/Animation/Animation.cpp.s
.PHONY : src/Animation/Animation.s

# target to generate assembly for a file
src/Animation/Animation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Animation/Animation.cpp.s
.PHONY : src/Animation/Animation.cpp.s

src/AudioManager/AudioManager.o: src/AudioManager/AudioManager.cpp.o
.PHONY : src/AudioManager/AudioManager.o

# target to build an object file
src/AudioManager/AudioManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/AudioManager/AudioManager.cpp.o
.PHONY : src/AudioManager/AudioManager.cpp.o

src/AudioManager/AudioManager.i: src/AudioManager/AudioManager.cpp.i
.PHONY : src/AudioManager/AudioManager.i

# target to preprocess a source file
src/AudioManager/AudioManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/AudioManager/AudioManager.cpp.i
.PHONY : src/AudioManager/AudioManager.cpp.i

src/AudioManager/AudioManager.s: src/AudioManager/AudioManager.cpp.s
.PHONY : src/AudioManager/AudioManager.s

# target to generate assembly for a file
src/AudioManager/AudioManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/AudioManager/AudioManager.cpp.s
.PHONY : src/AudioManager/AudioManager.cpp.s

src/Background/Background.o: src/Background/Background.cpp.o
.PHONY : src/Background/Background.o

# target to build an object file
src/Background/Background.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Background/Background.cpp.o
.PHONY : src/Background/Background.cpp.o

src/Background/Background.i: src/Background/Background.cpp.i
.PHONY : src/Background/Background.i

# target to preprocess a source file
src/Background/Background.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Background/Background.cpp.i
.PHONY : src/Background/Background.cpp.i

src/Background/Background.s: src/Background/Background.cpp.s
.PHONY : src/Background/Background.s

# target to generate assembly for a file
src/Background/Background.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Background/Background.cpp.s
.PHONY : src/Background/Background.cpp.s

src/Bus/Bus.o: src/Bus/Bus.cpp.o
.PHONY : src/Bus/Bus.o

# target to build an object file
src/Bus/Bus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Bus/Bus.cpp.o
.PHONY : src/Bus/Bus.cpp.o

src/Bus/Bus.i: src/Bus/Bus.cpp.i
.PHONY : src/Bus/Bus.i

# target to preprocess a source file
src/Bus/Bus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Bus/Bus.cpp.i
.PHONY : src/Bus/Bus.cpp.i

src/Bus/Bus.s: src/Bus/Bus.cpp.s
.PHONY : src/Bus/Bus.s

# target to generate assembly for a file
src/Bus/Bus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Bus/Bus.cpp.s
.PHONY : src/Bus/Bus.cpp.s

src/Bus/BusListener.o: src/Bus/BusListener.cpp.o
.PHONY : src/Bus/BusListener.o

# target to build an object file
src/Bus/BusListener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Bus/BusListener.cpp.o
.PHONY : src/Bus/BusListener.cpp.o

src/Bus/BusListener.i: src/Bus/BusListener.cpp.i
.PHONY : src/Bus/BusListener.i

# target to preprocess a source file
src/Bus/BusListener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Bus/BusListener.cpp.i
.PHONY : src/Bus/BusListener.cpp.i

src/Bus/BusListener.s: src/Bus/BusListener.cpp.s
.PHONY : src/Bus/BusListener.s

# target to generate assembly for a file
src/Bus/BusListener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Bus/BusListener.cpp.s
.PHONY : src/Bus/BusListener.cpp.s

src/Bus/BusWriter.o: src/Bus/BusWriter.cpp.o
.PHONY : src/Bus/BusWriter.o

# target to build an object file
src/Bus/BusWriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Bus/BusWriter.cpp.o
.PHONY : src/Bus/BusWriter.cpp.o

src/Bus/BusWriter.i: src/Bus/BusWriter.cpp.i
.PHONY : src/Bus/BusWriter.i

# target to preprocess a source file
src/Bus/BusWriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Bus/BusWriter.cpp.i
.PHONY : src/Bus/BusWriter.cpp.i

src/Bus/BusWriter.s: src/Bus/BusWriter.cpp.s
.PHONY : src/Bus/BusWriter.s

# target to generate assembly for a file
src/Bus/BusWriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Bus/BusWriter.cpp.s
.PHONY : src/Bus/BusWriter.cpp.s

src/Bus/Message.o: src/Bus/Message.cpp.o
.PHONY : src/Bus/Message.o

# target to build an object file
src/Bus/Message.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Bus/Message.cpp.o
.PHONY : src/Bus/Message.cpp.o

src/Bus/Message.i: src/Bus/Message.cpp.i
.PHONY : src/Bus/Message.i

# target to preprocess a source file
src/Bus/Message.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Bus/Message.cpp.i
.PHONY : src/Bus/Message.cpp.i

src/Bus/Message.s: src/Bus/Message.cpp.s
.PHONY : src/Bus/Message.s

# target to generate assembly for a file
src/Bus/Message.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Bus/Message.cpp.s
.PHONY : src/Bus/Message.cpp.s

src/Difficulty/Difficulty.o: src/Difficulty/Difficulty.cpp.o
.PHONY : src/Difficulty/Difficulty.o

# target to build an object file
src/Difficulty/Difficulty.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Difficulty/Difficulty.cpp.o
.PHONY : src/Difficulty/Difficulty.cpp.o

src/Difficulty/Difficulty.i: src/Difficulty/Difficulty.cpp.i
.PHONY : src/Difficulty/Difficulty.i

# target to preprocess a source file
src/Difficulty/Difficulty.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Difficulty/Difficulty.cpp.i
.PHONY : src/Difficulty/Difficulty.cpp.i

src/Difficulty/Difficulty.s: src/Difficulty/Difficulty.cpp.s
.PHONY : src/Difficulty/Difficulty.s

# target to generate assembly for a file
src/Difficulty/Difficulty.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Difficulty/Difficulty.cpp.s
.PHONY : src/Difficulty/Difficulty.cpp.s

src/Effect/Effect.o: src/Effect/Effect.cpp.o
.PHONY : src/Effect/Effect.o

# target to build an object file
src/Effect/Effect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Effect/Effect.cpp.o
.PHONY : src/Effect/Effect.cpp.o

src/Effect/Effect.i: src/Effect/Effect.cpp.i
.PHONY : src/Effect/Effect.i

# target to preprocess a source file
src/Effect/Effect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Effect/Effect.cpp.i
.PHONY : src/Effect/Effect.cpp.i

src/Effect/Effect.s: src/Effect/Effect.cpp.s
.PHONY : src/Effect/Effect.s

# target to generate assembly for a file
src/Effect/Effect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Effect/Effect.cpp.s
.PHONY : src/Effect/Effect.cpp.s

src/Entity/Entity.o: src/Entity/Entity.cpp.o
.PHONY : src/Entity/Entity.o

# target to build an object file
src/Entity/Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Entity/Entity.cpp.o
.PHONY : src/Entity/Entity.cpp.o

src/Entity/Entity.i: src/Entity/Entity.cpp.i
.PHONY : src/Entity/Entity.i

# target to preprocess a source file
src/Entity/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Entity/Entity.cpp.i
.PHONY : src/Entity/Entity.cpp.i

src/Entity/Entity.s: src/Entity/Entity.cpp.s
.PHONY : src/Entity/Entity.s

# target to generate assembly for a file
src/Entity/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Entity/Entity.cpp.s
.PHONY : src/Entity/Entity.cpp.s

src/Game/Game.o: src/Game/Game.cpp.o
.PHONY : src/Game/Game.o

# target to build an object file
src/Game/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Game/Game.cpp.o
.PHONY : src/Game/Game.cpp.o

src/Game/Game.i: src/Game/Game.cpp.i
.PHONY : src/Game/Game.i

# target to preprocess a source file
src/Game/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Game/Game.cpp.i
.PHONY : src/Game/Game.cpp.i

src/Game/Game.s: src/Game/Game.cpp.s
.PHONY : src/Game/Game.s

# target to generate assembly for a file
src/Game/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Game/Game.cpp.s
.PHONY : src/Game/Game.cpp.s

src/Resolution/Resolution.o: src/Resolution/Resolution.cpp.o
.PHONY : src/Resolution/Resolution.o

# target to build an object file
src/Resolution/Resolution.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Resolution/Resolution.cpp.o
.PHONY : src/Resolution/Resolution.cpp.o

src/Resolution/Resolution.i: src/Resolution/Resolution.cpp.i
.PHONY : src/Resolution/Resolution.i

# target to preprocess a source file
src/Resolution/Resolution.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Resolution/Resolution.cpp.i
.PHONY : src/Resolution/Resolution.cpp.i

src/Resolution/Resolution.s: src/Resolution/Resolution.cpp.s
.PHONY : src/Resolution/Resolution.s

# target to generate assembly for a file
src/Resolution/Resolution.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/Resolution/Resolution.cpp.s
.PHONY : src/Resolution/Resolution.cpp.s

src/bulletHell.o: src/bulletHell.cpp.o
.PHONY : src/bulletHell.o

# target to build an object file
src/bulletHell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/bulletHell.cpp.o
.PHONY : src/bulletHell.cpp.o

src/bulletHell.i: src/bulletHell.cpp.i
.PHONY : src/bulletHell.i

# target to preprocess a source file
src/bulletHell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/bulletHell.cpp.i
.PHONY : src/bulletHell.cpp.i

src/bulletHell.s: src/bulletHell.cpp.s
.PHONY : src/bulletHell.s

# target to generate assembly for a file
src/bulletHell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/bulletHell.cpp.s
.PHONY : src/bulletHell.cpp.s

src/helperFunctions/helperFunctions.o: src/helperFunctions/helperFunctions.cpp.o
.PHONY : src/helperFunctions/helperFunctions.o

# target to build an object file
src/helperFunctions/helperFunctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/helperFunctions/helperFunctions.cpp.o
.PHONY : src/helperFunctions/helperFunctions.cpp.o

src/helperFunctions/helperFunctions.i: src/helperFunctions/helperFunctions.cpp.i
.PHONY : src/helperFunctions/helperFunctions.i

# target to preprocess a source file
src/helperFunctions/helperFunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/helperFunctions/helperFunctions.cpp.i
.PHONY : src/helperFunctions/helperFunctions.cpp.i

src/helperFunctions/helperFunctions.s: src/helperFunctions/helperFunctions.cpp.s
.PHONY : src/helperFunctions/helperFunctions.s

# target to generate assembly for a file
src/helperFunctions/helperFunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/valeriePecrage.dir/build.make CMakeFiles/valeriePecrage.dir/src/helperFunctions/helperFunctions.cpp.s
.PHONY : src/helperFunctions/helperFunctions.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... valeriePecrage"
	@echo "... extlibs/Collision/Collision.o"
	@echo "... extlibs/Collision/Collision.i"
	@echo "... extlibs/Collision/Collision.s"
	@echo "... src/Animation/Animation.o"
	@echo "... src/Animation/Animation.i"
	@echo "... src/Animation/Animation.s"
	@echo "... src/AudioManager/AudioManager.o"
	@echo "... src/AudioManager/AudioManager.i"
	@echo "... src/AudioManager/AudioManager.s"
	@echo "... src/Background/Background.o"
	@echo "... src/Background/Background.i"
	@echo "... src/Background/Background.s"
	@echo "... src/Bus/Bus.o"
	@echo "... src/Bus/Bus.i"
	@echo "... src/Bus/Bus.s"
	@echo "... src/Bus/BusListener.o"
	@echo "... src/Bus/BusListener.i"
	@echo "... src/Bus/BusListener.s"
	@echo "... src/Bus/BusWriter.o"
	@echo "... src/Bus/BusWriter.i"
	@echo "... src/Bus/BusWriter.s"
	@echo "... src/Bus/Message.o"
	@echo "... src/Bus/Message.i"
	@echo "... src/Bus/Message.s"
	@echo "... src/Difficulty/Difficulty.o"
	@echo "... src/Difficulty/Difficulty.i"
	@echo "... src/Difficulty/Difficulty.s"
	@echo "... src/Effect/Effect.o"
	@echo "... src/Effect/Effect.i"
	@echo "... src/Effect/Effect.s"
	@echo "... src/Entity/Entity.o"
	@echo "... src/Entity/Entity.i"
	@echo "... src/Entity/Entity.s"
	@echo "... src/Game/Game.o"
	@echo "... src/Game/Game.i"
	@echo "... src/Game/Game.s"
	@echo "... src/Resolution/Resolution.o"
	@echo "... src/Resolution/Resolution.i"
	@echo "... src/Resolution/Resolution.s"
	@echo "... src/bulletHell.o"
	@echo "... src/bulletHell.i"
	@echo "... src/bulletHell.s"
	@echo "... src/helperFunctions/helperFunctions.o"
	@echo "... src/helperFunctions/helperFunctions.i"
	@echo "... src/helperFunctions/helperFunctions.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

